CREATE DATABASE pantax DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

CREATE TABLE pantax.user (id INT UNSIGNED NOT NULL AUTO_INCREMENT, name VARCHAR(100) NOT NULL, password VARCHAR(20) NOT NULL, entity_type VARCHAR(20) NOT NULL,	entity_id INT UNSIGNED NOT NULL, date_created DATETIME NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB;
CREATE TABLE pantax.doctor (id INT UNSIGNED NOT NULL AUTO_INCREMENT, name VARCHAR(512) NOT NULL, degree VARCHAR(20) NOT NULL, primary_care VARCHAR(20) NOT NULL,	entity_id INT UNSIGNED NOT NULL, date_created DATETIME NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB;