CREATE TABLE pantax.doctors ( `ID` INT UNSIGNED AUTO_INCREMENT NOT NULL,  `Name` VARCHAR(256) NOT NULL, `Degree` TEXT UNICODE, PRIMARY KEY (ID)) ENGINE = InnoDB ROW_FORMAT = DEFAULT;
CREATE TABLE pantax.patients ( `ID` INT UNSIGNED AUTO_INCREMENT NOT NULL, `Name` VARCHAR(256) NOT NULL, PRIMARY KEY (ID)) ENGINE = InnoDB ROW_FORMAT = DEFAULT;
CREATE TABLE pantax.messages ( `ID` INT UNSIGNED AUTO_INCREMENT NOT NULL, `Text` TEXT UNICODE, PRIMARY KEY (ID)) ENGINE = InnoDB ROW_FORMAT = DEFAULT;
CREATE TABLE pantax.documents ( `ID` INT UNSIGNED AUTO_INCREMENT NOT NULL, `Name` VARCHAR(256) NOT NULL, `Type` VARCHAR(256) NOT NULL, `FilePath` VARCHAR(1024) NOT NULL, `Comments` TEXT UNICODE, PRIMARY KEY (ID)) ENGINE = InnoDB ROW_FORMAT = DEFAULT;
CREATE TABLE pantax.appointments ( `ID` INT UNSIGNED AUTO_INCREMENT NOT NULL, `DoctorId` INT UNSIGNED, `PatientId` INT UNSIGNED, `FromDate` DATETIME, `ToDate` DATETIME, PRIMARY KEY (ID)) ENGINE = InnoDB ROW_FORMAT = DEFAULT;
CREATE TABLE pantax.entity_code ( `ID` INT UNSIGNED AUTO_INCREMENT NOT NULL, `EntityId` INT UNSIGNED, `Code` VARCHAR(512) NOT NULL, PRIMARY KEY (ID)) ENGINE = InnoDB ROW_FORMAT = DEFAULT;
CREATE TABLE pantax.doctor_patient(`DoctorId` INT UNSIGNED, `PatientId` INT UNSIGNED, PRIMARY KEY (DoctorId, PatientId)) ENGINE = InnoDB ROW_FORMAT = DEFAULT;
CREATE TABLE pantax.doctor_document (`DoctorId` INT UNSIGNED, `DocumentId` INT UNSIGNED, PRIMARY KEY (DoctorId, DocumentId)) ENGINE = InnoDB ROW_FORMAT = DEFAULT;
CREATE TABLE pantax.message_document (`MessageId` INT UNSIGNED, `DocumentId` INT UNSIGNED, PRIMARY KEY (MessageId, DocumentId)) ENGINE = InnoDB ROW_FORMAT = DEFAULT;
CREATE TABLE pantax.message_patient (`MessageId` INT UNSIGNED, `PatientId` INT UNSIGNED, PRIMARY KEY (MessageId, PatientId)) ENGINE = InnoDB ROW_FORMAT = DEFAULT;
CREATE TABLE pantax.message_doctor (`MessageId` INT UNSIGNED, `DoctorId` INT UNSIGNED, PRIMARY KEY (MessageId, DoctorId)) ENGINE = InnoDB ROW_FORMAT = DEFAULT;
CREATE TABLE pantax.patient_document (`PatientId` INT UNSIGNED, `DocumentId` INT UNSIGNED, PRIMARY KEY (PatientId, DocumentId)) ENGINE = InnoDB ROW_FORMAT = DEFAULT;
CREATE TABLE pantax.doctor_appointment (`DoctorId` INT UNSIGNED, `AppointmentId` INT UNSIGNED, PRIMARY KEY (DoctorId, AppointmentId)) ENGINE = InnoDB ROW_FORMAT = DEFAULT;
CREATE TABLE pantax.patient_appointment (`PatientId` INT UNSIGNED, `AppointmentId` INT UNSIGNED, PRIMARY KEY (PatientId, AppointmentId)) ENGINE = InnoDB ROW_FORMAT = DEFAULT;
CREATE TABLE pantax.message_appointment (`MessageId` INT UNSIGNED, `AppointmentId` INT UNSIGNED, PRIMARY KEY (MessageId, AppointmentId)) ENGINE = InnoDB ROW_FORMAT = DEFAULT;

